apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-sm
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: springboot
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
